### ISSUE TITLE
lychee not working after upgrade to lycheeorg/lychee-laravel:dev (Image ID:0c3ea3c21b7f)

### ISSUE THREAD

**Issue by zhanglix** [LycheeOrg/Lychee-Laravel-Docker#52]
### Detailed description of the problem [REQUIRED]
I setup a Lychee Service using lycheeorg/lychee-larave:latest (Imag ID: 70e1024b8861)
with proper volumn and database setup. After sync some photos, the Lychee service works very well. Then I upgrade to lycheeorg/lychee-larave:dev,  and can not make it work anymore.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. docker run -d \
--name=lychee --restart=unless-stopped \
-v /srv/lychee/conf:/conf \
-v /srv/lychee/uploads:/uploads \
-e PUID=1000 \
-e PGID=1000 \
-e PHP_TZ=$(cat /etc/timezone ) \
-e DB_CONNECTION=mysql \
-e DB_HOST=172.17.0.1  \
-e DB_PORT=3306 \
-e DB_DATABASE=photos \
-e DB_USERNAME=lychee \
-e DB_PASSWORD=DBPassword \
-p 90:80 \
lycheeorg/lychee-laravel:latest

2. docker exec -it lychee php artisan lychee:sync /conf/path/to/photos

3. docker stop lychee && docker rename lychee lychee.bk
4. docker run -d \
--name=lychee --restart=unless-stopped \
-v /srv/lychee/conf:/conf \
-v /srv/lychee/uploads:/uploads \
-e PUID=1000 \
-e PGID=1000 \
-e PHP_TZ=$(cat /etc/timezone ) \
-e DB_CONNECTION=mysql \
-e DB_HOST=172.17.0.1  \
-e DB_PORT=3306 \
-e DB_DATABASE=photos \
-e DB_USERNAME=lychee \
-e DB_PASSWORD=DBPassword \
-p 90:80 \
lycheeorg/lychee-laravel:dev

after login,  get some fatal error.

**Screenshots**
![Screen Shot 2020-05-13 at 1 01 02 AM](https://user-images.githubusercontent.com/8109462/81808828-e6c8d600-9552-11ea-99a3-5555b229237b.png)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics )*

   Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       master (cda45c2) - Data not in Cache
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    ------------------
    version:                    040003
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     0
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        1
    landing_owner:              -
    landing_title:              -
    landing_subtitle:          -
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  1
    SL_for_admin:               1
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0

**Comment by d7415** [comment]
Try setting `APP_DEBUG=true` in your `conf/.env` file. That should give a more helpful response in the network tab of the inspector when the error is raised.

**Comment by zhanglix** [comment]
After seting debug=true, got the same error.
<img width="1440" alt="Screen Shot 2020-05-13 at 8 35 51 PM" src="https://user-images.githubusercontent.com/8109462/81812921-5f329580-9559-11ea-93f1-f84743f1b60b.png">

 Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       master (cda45c2) - Data not in Cache
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

**Comment by ildyria** [comment]
You are providing a screenshot of the console, not the response of `Albums::get` in the **network** tab.

**Comment by zhanglix** [comment]
sorry.

<img width="1440" alt="Screen Shot 2020-05-13 at 10 26 27 PM" src="https://user-images.githubusercontent.com/8109462/81825143-d91e4b00-9568-11ea-87ae-ca6a10e0fef1.png">

It seems that there are something wrong with the /sym directory?

```lang=sh
root@1201a4f2296c:/var/www/html/Lychee# ls -l --color=auto  /sym
total 0
-rw-r--r-- 1 lychee lychee 0 May 12 16:49 empty_file
```




```lang=js
{
    "message": "unlink(/sym/40cdfa8f8912a0e32fd00d417c5e19095849ab08ab21a503ea04f4f397409c66.JPG): No such file or directory",
    "exception": "ErrorException",
    "file": "/var/www/html/Lychee/app/SymLink.php",
    "line": 99,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/SymLink.php",
            "line": 99,
            "function": "unlink"
        },
        {
            "file": "/var/www/html/Lychee/app/SymLink.php",
            "line": 121,
            "function": "create",
            "class": "App\\SymLink",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/SymLinkFunctions.php",
            "line": 52,
            "function": "set",
            "class": "App\\SymLink",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 159,
            "function": "find",
            "class": "App\\ModelFunctions\\SymLinkFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 526,
            "function": "gen_thumbs",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 318,
            "function": "get_albums",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Controllers/AlbumsController.php",
            "line": 59,
            "function": "prepare_albums",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "function": "get",
            "class": "App\\Http\\Controllers\\AlbumsController",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 76,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Middleware/VerifyCsrfToken.php",
            "line": 60,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php",
            "line": 39,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 116,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 62,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/public/index.php",
            "line": 79,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
```

**Comment by zhanglix** [comment]
I the dev container :
```
root@1201a4f2296c:/var/www/html/Lychee# ls public/sym
empty_file
```
In the working container:
```
root@8c5d7f3760e5:/var/www/html/Lychee-Laravel# ls public/sym/|head -2
xxxxxx.jpeg
yyyyyy.JPG
```

should I copy this directory to the new container?

**Comment by zhanglix** [comment]
Or are there any tool to rebuild the sym directory?

**Comment by d7415** [comment]
Yes, the error is because the files don't exist. Copying them across would be the easiest fix. That's why /sym is set up as a volume. Alternatively, I think turning the symlink function off should fix it or at least stop the error.

**Comment by d7415** [comment]
Actually, Looking at the code that raised the error, did you move your images? It looks like it's failing because the original doesn't exist

**Comment by zhanglix** [comment]
> Actually, Looking at the code that raised the error, did you move your images (the /uploads volume)? It looks like it's failing because the original doesn't exist

No. I didn't move any file in uploads directory.

**Comment by d7415** [comment]
> No. I didn't move any file in uploads directory.

As in, did you move them to the new container? If you didn't, that's why it's breaking - It has no files.

**Comment by zhanglix** [comment]
I just forget to  mount /sym as a volume at first.  now I move the sym directory  to the host and mount it as a volume now.

but it still not working. the file 54a3360d052b251c5695bb46645ccd248d289d54596266d3e3abf2e557694acb.JPG is still missing.
```lang=js

{
    "message": "unlink(/sym/54a3360d052b251c5695bb46645ccd248d289d54596266d3e3abf2e557694acb.JPG): No such file or directory",
    "exception": "ErrorException",
    "file": "/var/www/html/Lychee/app/SymLink.php",
    "line": 99,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/SymLink.php",
            "line": 99,
            "function": "unlink"
        },
        {
            "file": "/var/www/html/Lychee/app/SymLink.php",
            "line": 121,
            "function": "create",
            "class": "App\\SymLink",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/SymLinkFunctions.php",
            "line": 52,
            "function": "set",
            "class": "App\\SymLink",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 159,
            "function": "find",
            "class": "App\\ModelFunctions\\SymLinkFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 526,
            "function": "gen_thumbs",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 318,
            "function": "get_albums",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Controllers/AlbumsController.php",
            "line": 59,
            "function": "prepare_albums",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "function": "get",
            "class": "App\\Http\\Controllers\\AlbumsController",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 76,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Middleware/VerifyCsrfToken.php",
            "line": 60,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php",
            "line": 39,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 116,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 62,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/public/index.php",
            "line": 79,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}
```
unfortunetely  I think I lost lots of links by ```mv public/sym /conf/```

After I mount sym  to a new lychee-laravel:latest container, lots of thumbs are missing.
I think I should re-sync all my photos again.

<img width="1440" alt="Screen Shot 2020-05-13 at 11 41 58 PM" src="https://user-images.githubusercontent.com/8109462/81834534-a299fd80-9573-11ea-804d-6e2a54707dcf.png">

**Comment by zhanglix** [comment]
I think I should close this  issue because I forget to mount /sym as volume at first.

**Comment by d7415** [comment]
> unfortunetely I think I lost lots of links by `mv public/sym /conf/`

The sym folder shouldn't be in conf (with the normal docker setup anyway). The entrypoint script creates a symlink from /sym (which is defined as a volume in the image) and /var/www/html/Lychee/public/sym. For both of your containers, the symlinks should be in /sym.

> After I mount sym to a new lychee-laravel:latest container, lots of thumbs are missing.
Yes. They're using symlinks that don't exist. If you turn off the symlinks in your settings I suspect you'll find they work.

> I think I should re-sync all my photos again.
That may be easiest, but if you do this it may be worth clearing out /sym and your albums/photos first.

**Comment by zhanglix** [comment]
> > unfortunetely I think I lost lots of links by `mv public/sym /conf/`
> 
> The sym folder shouldn't be in conf (with the normal docker setup anyway). The entrypoint script creates a symlink from /sym (which is defined as a volume in the image) and /var/www/html/Lychee/public/sym. For both of your containers, the symlinks should be in /sym.

I know, It is just a simple way to move it to the host without use docker cp :)
